name: tts_flow_workspace
description: Melos-managed mono repo workspace for tts_flow_dart packages.
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - apps/tts_flow_dart_example
  - packages/tts_flow_dart

dev_dependencies:
  melos: ^7.0.0
