name: tts_flow_flutter
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  flutter:
    sdk: flutter
  tts_flow_dart: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0
