name: tts_flow_dart_example
description: Example app for tts_flow_dart.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  tts_flow_dart: ^0.1.0

dev_dependencies:
  lints: ^5.0.0
